# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscleGroupId',
            field=models.IntegerField(default=0),
        ),
    ]
